### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by sraza1999** [aspose-words/Aspose.Words-for-Python-via-.NET#16]
Hello,

The pip install does not seem to be working.
![Screen Shot 2022-06-06 at 9 20 21 PM](https://user-images.githubusercontent.com/19677225/172281861-c50d7ece-7c0e-4aa6-9225-751d52a76d7d.png)

**Comment by AlexNosk** [comment]
@sraza1999 Could you please let me know in what environment the problem occurs and which version of python you are using. I have checked on my side and `aspose-words` package is properly installed.

**Comment by sraza1999** [comment]
I'm on Mac 10.15.4 and running Python version 3.7.6

**Comment by AlexNosk** [comment]
@sraza1999  Unfortunately, Aspose.Words for Python does not support MacOS yet. Currently only Windows and Linux operation systems are supported. Please see our documentation for more information:
<https://docs.aspose.com/words/python-net/system-requirements/>

**Comment by AlexNosk** [comment]
@sraza1999 If everything goes smoothly MacOS will be supported after 22.8 version of Aspose.Words for Python (August-September 2022).

**Comment by AlexNosk** [comment]
@ssraza21 We are glad to let you know that the latest 23.12 version of [Aspose.Words for Python](https://pypi.org/project/aspose-words/) supports MacOS ARM architecture.
