### ISSUE TITLE
Support for mac

### ISSUE THREAD

**Issue by Bogenrieder** [aspose-words/Aspose.Words-for-Python-via-.NET#20]
Dear Developers,

Your library seems very promising! I am looking forward to using it.
However, Apsose.words does not seem to work on my M1 macbook (2020).
Could you please make a build for it?

Best regards
Lukas

**Comment by AlexNosk** [comment]
@Bogenrieder Currently we plan to deliver MacOS x86 version in October-November 2022. The appropriate request is logged as **WORDSNET-24045** in our internal defect tracking system. Unfortunately, currently there is no estimates regarding arm64 version yet.

**Comment by AlexNosk** [comment]
@Bogenrieder Thank you for your feedback. We will consider reprioritizing the platforms.

**Comment by Bogenrieder** [comment]
Thank you for reconsidering.
I looking forward to when your library becomes available on mac!
So far, I am using the great but sadly now unmaintained python-docx library and adding functionality myself to make it closer to aspose.words manually. It's not the ideal solution...

**Comment by texzone** [comment]
Hello team,

Thank you for all your hard word. Any updates on this potentially?

**Comment by Cglezf** [comment]
I agree, waiting for support to mac x86 and M# processors

**Comment by LouisLecouturier** [comment]
I'm interested too..

**Comment by WilliamWCYoung** [comment]
Same! Shame as the underlying .net packages work on arm

**Comment by AlexNosk** [comment]
Unfortunately, .NET to Python wrapper does not currently support the M1 processor. Our wrapper team is working on this, but currently no estimates.
