### ISSUE TITLE
Python 3.11.0 not supported

### ISSUE THREAD

**Issue by m-passmore** [aspose-words/Aspose.Words-for-Python-via-.NET#26]
Hi, I have had to update my python due to security issues with the old version. However, now aspose-words does not work. Is there a solution for this?

**Comment by stdstring** [comment]
Hello. Aspose.Words for Python via .NET doesn't support Python 3.11 now. We are working on this problem and plan to add support of Python 3.11 into Aspose.Words for Python via .NET in one of the nearest releases.

**Comment by stdstring** [comment]
Hello. Aspose.Words for Python via .NET supports Python 3.11 started from version 23.1 (https://pypi.org/project/aspose-words/)
