### ISSUE TITLE
i am wondering why converting from jpg/png to svg gives nothing content in converted svg, when i run the code on my local environment?

### ISSUE THREAD

**Issue by Matt-JyS** [aspose-words/Aspose.Words-for-Python-via-.NET#37]
when i use the online converter provided by you, everything is fine. but when i copy the code to run on my own pc. The generated svg is blank, no content inside of it. Could you please give some tips?

This is the code provided by you:
```py
import aspose.words as aw
doc = aw.Document()
builder = aw.DocumentBuilder(doc)
shape = builder.insert_image("Input.jpg")
shape.image_data.save("Output.svg")
```
Thank you so much !!

**Comment by AlexNosk** [comment]
@Matt-JyS Could you please attach your `"Input.jpg"` here for testing? Also, could you please provide information about the environment where the code is run? We will check the issue and provide you more information. 

PS: The main place or getting support is Aspose.Words support forum. So please post your questions in the forum to get timely response: <https://forum.aspose.com/c/words/8>

**Comment by Matt-JyS** [comment]
Thank you Alex for your timely reply and reminder. Sure, I will ask for support directly from the forum you have given then.
