### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by Anonymous6598** [aspose-words/Aspose.Words-for-Python-via-.NET#54]
When are you going to add python 3.12 as supported version for aspose-words? I have been waiting 7 months and still no release, which supports python 3.12!

**Comment by Anonymous6598** [comment]
Thanks for feedback.

**Comment by Anonymous6598** [comment]
Hello @AlexNosk!
Do you have news about python 3.12 support?
@Anonymous6598.

**Comment by AlexNosk** [comment]
@Anonymous6598 There are no news regarding the issue yet. We will be sure to keep you updated and let you know once python 3.12 version is supported.

**Comment by Anonymous6598** [comment]
Hello @AlexNosk!
Do you have news about python 3.12 support?
@Anonymous6598

**Comment by AlexNosk** [comment]
@Anonymous6598 Unfortunately, there are no news yet.

**Comment by Anonymous6598** [comment]
Thanks for info

**Comment by Anonymous6598** [comment]
Hello @AlexNosk!
Do you have any news about python 3.12 support?
@Anonymous6598

**Comment by AlexNosk** [comment]
@Anonymous6598 Unfortunately, there are no news yet.

**Comment by Anonymous6598** [comment]
Hello @AlexNosk!
Do you have any news about python 3.12 support?
@Anonymous6598

**Comment by AlexNosk** [comment]
@Anonymous6598 There are no news yet. Please accept our apologies for your inconvenience.

**Comment by Anonymous6598** [comment]
Do you have issues with adapting aspose-words api to new python version?

**Comment by AlexNosk** [comment]
@Anonymous6598 No, there are no any issues. Our porter team is working on this and we in Aspose.Words team are waiting for implementation of this feature in the porter.

**Comment by Anonymous6598** [comment]
I hope so because python 3.13 will be soon released

**Comment by Anonymous6598** [comment]
Hello @AlexNosk!
Do you have any news about python 3.12 support?
@Anonymous6598

**Comment by AlexNosk** [comment]
@Anonymous6598 I am afraid there are not news yet.

**Comment by Anonymous6598** [comment]
Again? So next version also will not support python 3.12?

**Comment by AlexNosk** [comment]
@Anonymous6598 I have checked with the development team. If everything goes smoothly the next version will include support of Python 3.12.

**Comment by Anonymous6598** [comment]
That's great

**Comment by Anonymous6598** [comment]
Just notify me please

**Comment by Anonymous6598** [comment]
Hello @AlexNosk,
You told me that the next update would feature python 3.12 before. Does current aspose.words API feature support of python 3.12?
@Anonymous6598

**Comment by AlexNosk** [comment]
@Anonymous6598 24.6 version does not include support of 3.12 version of Python. it's support will be included into 24.7 version if testing goes well.

**Comment by Anonymous6598** [comment]
I hope

**Comment by AlexNosk** [comment]
@Anonymous6598 We have published [Aspose.Words for Python 24.7](https://pypi.org/project/aspose-words/) with supporting Python 3.12

**Comment by Anonymous6598** [comment]
Hello @AlexNosk! Thank you for telling me! Now I can upgrade my apps and change python version. Thank you! 👍
