### ISSUE TITLE
Add Red Hat ubi9 example to Dockerfile for Python 3.11

### ISSUE THREAD

**Issue by Cerebex** [aspose-words/Aspose.Words-for-Python-via-.NET#60]
Can an example linux deployment starting with [Red Hat ubi9](https://catalog.redhat.com/software/containers/ubi9/ubi/615bcf606feffc5384e8452e?architecture=amd64&image=664f601144727717ac47958f) as the base image be added to the Dockerfile for python 3.11?

**Comment by AlexNosk** [comment]
@Cerebex We have logged a feature request. Please see the following forum topic for more details:
<https://forum.aspose.com/t/aspose-words-for-python-via-net-red-hat-ubi9-example-dockerfile-for-python-3-11/284907>
