### ISSUE TITLE
word sign password 

### ISSUE THREAD

**Issue by zhongsdjn** [aspose-words/Aspose.Words-for-Python-via-.NET#8]
hi! `aw.digitalsignatures.CertificateHolder.create(MY_DIR + "morzal.pfx", "aw")`   on windows system no problem!but complex password can't decrypt on unix like centos， only “aw”!

你好！word文档加密电子签名设置的密码基本在windows系统没问题，但是在类unix系统 如centos7 只能(猜测)使用`aw.digitalsignatures.CertificateHolder.create(MY_DIR + "morzal.pfx", "aw")` aw为密码  其它如123456/nihao/nihao123等等都不能用！请问是什么原因？提示`RuntimeError: Proxy error(InvalidCastException) or other tips`

**Comment by AlexNosk** [comment]
@zhongsdjn If you use the PFX file from the examples repository for testing, then you must use `aw` password. This is the password to access certificate data. If you pass other password, you will get exception like this:
`PKCS12 key store MAC invalid - wrong password or corrupted file.`
Could you please provide a full error message you get or if possible sample PFX file? We will further investigate the issue and provide you more information.
I tried using another PFX file on my side with `1234567890` password and it works fine.

**Comment by AlexNosk** [comment]
No feedback and cannot reproduce. Close.
